import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

const neueMachina = localFont({
  src: [
    {
      path: "../public/fonts/neuemachina/NeueMachina-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/neuemachina/NeueMachina-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/neuemachina/NeueMachina-Ultrabold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-neue-machina",
});


export const metadata: Metadata = {
  title: "Moonex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${neueMachina.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
